/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M10
 * Generated at: 2016-11-28 06:47:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import java.util.List;
import recommend.*;
import dbHandling.*;

public final class RecommendMain_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("recommend");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("dbHandling");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	DBHandler dbHandler = new DBHandler();
	//dbHandler.setData();
	Recommender recommender = new Recommender(); 
	ArrayList<MovieInfo> movieInfos = dbHandler.getData();
	List<RecommendInfo> list = new ArrayList<>();
	
	for(int i=0;i<movieInfos.size();i++)
		recommender.addMovie(movieInfos.get(i));

	MovieInfo info = new MovieInfo("", "Test1", "","","","","","","액션,드라마","","액션");
	recommender.addMovie(info);
	info = new MovieInfo("", "Test2", "","","","","","","코미디,드라마","","드라마");
	recommender.addMovie(info);
	info = new MovieInfo("", "Test3", "","","","","","","가족,멜로/로맨스","","가족");
	recommender.addMovie(info);
	info = new MovieInfo("", "Test4", "","","","","","","코미디","","");
	recommender.addMovie(info);
	info = new MovieInfo("", "당신이 사랑하는 동안에2", "","","","","","","드라마,멜로/로맨스,스릴러","","드라마");
	recommender.addMovie(info);
	
	recommender.addPerson("p1");
	for(int i=0;i<movieInfos.size();i++){
		if(movieInfos.get(i).getMovieData().getRepGenreNm().equals("액션"))
			recommender.setRate("p1", movieInfos.get(i).getMovieData().getMovieCd(), 4.5);
		else if(movieInfos.get(i).getMovieData().getRepGenreNm().equals("드라마"))
			recommender.setRate("p1", movieInfos.get(i).getMovieData().getMovieCd(), 4.9);
		else if(movieInfos.get(i).getMovieData().getRepGenreNm().equals("판타지"))
			recommender.setRate("p1", movieInfos.get(i).getMovieData().getMovieCd(), 0.5);
		else if(movieInfos.get(i).getMovieData().getRepGenreNm().equals("기티"))
			recommender.setRate("p1", movieInfos.get(i).getMovieData().getMovieCd(), 1.5);
		else
			recommender.setRate("p1", movieInfos.get(i).getMovieData().getMovieCd(), 3);
	}

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=EUC-KR\">\r\n");
      out.write("<title>Movie Recommend</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

	list = recommender.getRecommend("p1");
	for(int i=0;i<list.size();i++){
		out.print("<p>"+i+"위: "+ list.get(i).getName() + "     평점: "+ list.get(i).getRate()+"</p>");
	}
 
      out.write("\r\n");
      out.write(" </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
